- Lizard_bot_rsf.py
- create_db.sql
Updated to match the newest non-DB update
Still no error checking
`- Nog`
> TOs and Bot Role

- Lizard_bot_rsf.py
I also fixed a bad thing where if someone could type can we play before the settings exist and things would explode
`- Nog`
> Prefix is editable per channel

- Lizard_bot_rsf.py
Added prefix-lizard and bot_role to get info about those
`- Nog`
> Some clean up and new commands

- Lizard_bot_rsf.py
- README.md
- create_db.sql
Trimmed duplicate save, read, and initial data save
Added coin-flip
Added the dash to !prefix-lizard in README
`- Nog`
> Refactoring, coin flip, and fixes

- Lizard_bot_rsf.py
> One last fix

- README.md
- bots.json
- commands.py
- create_db.sql
- utilities.py
Multi-channel edit commands are now functional. Code for checking only the first parameters is sloppy but I couldn't think of another way. 
Added support for bracket command
As always, test before merging.
`- Nog`
>  Multi-channel Updates 

- bot.py
- commands.py
Removed the per channel printing when editing commands
`- Nog`
> Limit channel spam

- bot.py
Quick fix for the empty command
`- Nog`
> Fix for empty command

- doc/sheets_integration.md
Fixed the part where there is no explanation of enabling Google Sheets API
`- Nog`
> Updated to enable Google Sheets API properly

- bot/commands/utilities.py
Fixes the error with non-Challonge Users breaking things
`- Nog`
> Catching non-Challonge Users

- bot/commands/commands.py
- bot/commands/sheets/sheets.py
- bot/commands/utilities.py
Corrected the issue with the seeding and made it easier to see if something broke
`- Nog`
> Correct Seeding and Add Error Catch All

- bot/commands/bots.json
- bot/commands/commands.py
Allowed the shortened version of the randomselect command
`- Nog`
> Add shortened randomselect

- bot/bot.py
- bot/commands/bots.json
- bot/commands/commands.py
- bot/interface.py
Added shorthand commands, additional return messages for errors, and moved prefix-lizard to common commands
`- Nog`
> Quality of Life improvements

- README.md
- bot/bot.py
- bot/commands/bots.json
- bot/commands/commands.py
- bot/commands/utilities.py
- bot/interface.py
Wrote up the shell for a better help command. Edit the last array entry in bots.json to edit what is displayed
`- Nog`
> Improved help command

- bot/commands/bots.json
- bot/commands/commands.py
- bot/commands/utilities.py
- bot/interface.py
> Fixing Help for Improved Challonge

- bot/commands/bots.json
- bot/commands/commands.py
- bot/commands/utilities.py
- bot/interface.py
Fixed bug where the refresh command didnt work. thought command was the description
> Added a description to refresh so it works properly

- bot/bot.py
- bot/commands/bots.json
- bot/commands/commands.py
- bot/interface.py
Didn't do full regression testing but I did confirm that not-in-discord worked with challonge checkin and that the stacktrace is printed to console.
`-Nog`
> (Not in Discord and Proper Error Printing) with a New Status

- README.md
- bot/bot.py
- bot/commands/utilities.py
Updated bot to new version of discord.py. In order to get list of users we now need member intent. I have added the necessary lines in the bot itself as well as enabled it via the discord developer dashboard.
checkin fixed and updated. Now checks if the challonge name is contained in any part of a username in discord.
Fixed SFV not being capitalized
> Added member intent, fixed and updated checkin

- README.md
- doc/new_bot_setup.md
- doc/seeding_with_sheets.md
- doc/setting_up_bot_in_discord.md
Mostly spelling/grammar corrections
`-Nog`
> More documentation edits

- doc/setting_up_bot_in_discord.md
Hopefully this makes sure the images aren't in line with the start of the text
> Fixed spacing on images

- bot/bot.py
- bot/commands/bots.json
- bot/commands/commands.py
Also added comments for some sections that I missed
`-Nog`
> Issue #37: Fixed responding to no arg commands with args sent

- bot/bot.py
- bot/commands/commands.py
Changed the check from the length of the args passed to see if the first arg was empty
Fixes  lizardman301/Lizard-bot-rsf#39
`-Nog`
> Fixed the help command

- bot/bot.py
Allows bot to resond to @ mentions with a simple response. Closes #41
> Added response to mentions

- bot/commands/commands.py
- bot/interface.py
Also adds a more unique catch-all error message
Fixes #48
`-Nog`
> !stats produces unique error for invalid subcommand

- bot/bot.py
- bot/commands/commands.py
- bot/commands/sheets/sheets.py
- bot/commands/utilities.py
- bot/interface.py
Changed error messages to Exceptions
Added ExceptionHandling to some edge cases
Moved ExceptionHandling to bot.py over interface.py to catch database issues
Database errors should mostly be prevented now
Fixes #53
Fixes #54
`-Nog`
> Errors are now Exceptions

- README.md
- bot/commands/bots.json
- bot/commands/commands.py
- doc/bot_commands.md
I have freed the chains around botrole
Updated the documentation as well
Closes #55 
`-Nog`
> DeCriminalize Botrole

- README.md
- bot/commands/bots.json
- bot/commands/commands.py
- bot/commands/utilities.py
- doc/bot_commands.md
- sql/create_db.sql
Added DB option for !pingtest
Added Exception handling for failing to read/write to DB
Closes #62 
`-Nog`
> Customizable Pingtest

- bot/bot.py
- bot/commands/commands.py
- bot/commands/sheets/sheets.py
- bot/commands/utilities.py
Corrected !help-lizard only accepting exact capitalization. Closes #69
Stopped !prefix-lizard accepting arguments
Corrected !edit prefix-lizard to set !prefix-lizard to nothing. Closes #71
Correct the Exception handling for !remind so that a user knows they must enter a positive integer. Closes #74
Moved opening and parsing of rs.json to utilities.py from commands.py (draw and randomselect). Closes #73
Narrowed the scope of module importing to help decrease load times. Closes #72
Corrected `!TOs` still accepting arguments
Corrected `!challonge seeding` taking non-positive non-integer values. Closes #75
Corrected `!edit status` not checking to make sure there is a `{0}` in the string. Closes #76
Corrected `!status` which unexpected error when `!status` contained `{1}` or multiple `{}`. …
> Bundle of fixes/adjustments

- bot/commands/commands.py
Very quick update to make this thing work properly
> Added .lower() to enable/disable

- bot/commands/commands.py
- fixed !draw finishing prematurely when an unexpected reaction is used on the message. Closes #88 
- fixed bug where if another player reacted to the a banned/picked character, it would react as if the player picked that character.
- added option to decline draw
> fixed !draw failing on unexpected reaction

- bot/commands/commands.py
Fixed TimeoutError not closing out the draw command
> fixed timeout error not closing out !draw

- bot/commands/utilities.py
Trying to mitigate errors occurring from overdrawing out connections
Fixes #103 
`-Nog`
> Increase max conns and wait timeout

- bot/commands/rs.json
New update just dropped today. Added to the !randomselect and !stageselect command
> Added new tekken stage and character

- bot/bot.py
- bot/commands/bots.json
- bot/commands/challonge.py
- bot/commands/commands.py
- bot/commands/sheets/sheets.py
- bot/interface.py
Closes #101
Also removed some unused dependencies
`-Nog`
> Nogarremi finally comments his code

- bot/commands/challonge.py
- bot/commands/utilities.py
`!challonge seeding` now randomizes the seeds before seeding
Added some additional messaging to Challonge errors to explain what part breaks
Closes #111 
`-Nog`
> !challonge seeding randomizes seeds

- bot/commands/rs.json
Added Rose for SFV and Eustace for GBVS into rs.json
> Added Rose and Eustace

- bot/commands/commands.py
- sql/create_db.sql
Closes #114 
Updated what the default value for `disabled_list` should be
Added additional checking to `!botrole`
`-Nog`
> !botrole failing on new guild

- bot/bot.py
- bot/commands/challonge.py
- bot/commands/commands.py
- bot/commands/edit.py
- bot/commands/utilities.py
- bot/interface.py
Reverted changes from tormysql to pymysql due to lingering instabilities
Resolves #116 
`-Nog`
> Reverting back to pymysql

- bot/bot.py
- bot/commands/bots.json
- bot/commands/commands.py
- bot/commands/utilities.py
- bot/interface.py
Added support for a developer command to assist in not having direct access to the database
This is limited by Discord user IDs and a specific developer Discord server to prevent unwanted access
Closes #119 
`-Nog`
> Allow remote DB access for devs

- bot/commands/commands.py
Resolved the issue with invalid random type raising an unknown error
Resolves #121 
`-Nog`
> Invalid Random Type

- .gitignore
- bot/bot.py
- bot/commands/commands.py
- bot/commands/rs.json
- bot/commands/utilities.py
- Created a way to read Infil's Fighting Game Glossary(TM) and print it inline
`-Nog`
> Glossary updated to print inline

- bot/commands/rs.json
Added melty blood to randomselect for the new game.
> Add melty blood to rs.json

- bot/utilities/rs.json
Quick update for new DLC characters
GBVS: Vira, Avatar Belial
MBTL: Dead Apostle Noel, Aoko Aozaki
SFV: Luke
GGST: Happy Chaos, Baiken (Not released yet)
`-Nog`
> Update rs.json (Jan 2022)

- bot/commands/rs.json
Quick update for new DLC characters
GBVS: Vira, Avatar Belial
MBTL: Dead Apostle Noel, Aoko Aozaki
SFV: Luke
GGST: Happy Chaos, Baiken (Not released yet)
`-Nog`
>  Update rs.json (Jan 2022) (Python)

- .gitignore
- bot/bot.py
- bot/commands/bots.json
- bot/commands/commands.py
- bot/commands/edit.py
> Created `!matcherino` command
